#%RAML 1.0 DataType

/name/: !include apis/assets_get_set_name.raml
/records/{id}/: !include apis/assets_get_set_records_by_id.raml
/records/{id}/get_sub_records: !include apis/assets_get_sub_records_by_id.raml
