#%RAML 1.0

title: REST

documentation:
  - title: Introduction
    content: |
     This document defines the definition of HTTP interfaces which will be used
     by Browser to communicate with middleware.
     The JSON requests/responses of these HTTP interfaces are designed specific to UI.
  - title: Copyright
    content: |
     Copyright (C) SheelRana 2017

     The reduction, transmission or use of this document  or its contents
     is not  permitted without  prior express written consent of SheelRana.
     Offenders will be liable for damages. All rights, including  but not
     limited to rights created by patent grant or registration of a utility
     model or design, are reserved.

     SheelRana reserves the right to modify technical specifications and features.

     Technical specifications and features are binding only in so far as they
     are specifically and expressly agreed upon in a written contract.

version: 1.0
baseUri: /
mediaType: application/json

types: !include apis/entities/all-entities.raml

/human: !include PROJECT_NAME_HUMAN.raml
/machines: !include PROJECT_NAME_MACHINE.raml
/assets: !include PROJECT_NAME_ASSETS.raml
