#%RAML 1.0 DataType

#=============================
# Entities for Assets
#=============================
AssetsGetSetNameRequest:
  schema: !include Assets/schemas/Request/AssetsGetSetNameRequest.json
  example: !include Assets/examples/Request/AssetsGetSetNameRequest.json
AssetsGetSetNameReResponse:
  schema: !include Assets/schemas/Response/AssetsGetSetNameReResponse.json
  example: !include Assets/examples/Response/AssetsGetSetNameReResponse.json

AssetsGetRecordsByIdRequest:
  schema: !include Assets/schemas/Request/AssetsGetSetRecordsByIdRequest.json
  example: !include Assets/examples/Request/AssetsGetSetRecordsByIdRequest.json
AssetsGetSetRecordsByIdResponse:
  schema: !include Assets/schemas/Response/AssetsGetSetRecordsByIdResponse.json
  example: !include Assets/examples/Response/AssetsGetSetRecordsByIdResponse.json

AssetsSetRecordsByIdRequest:
  schema: !include Assets/schemas/Request/AssetsSetRecordsByIdRequest.json
  example: !include Assets/examples/Request/AssetsSetRecordsByIdRequest.json
AssetsSetRecordsByIdResponse:
  schema: !include Assets/schemas/Response/AssetsSetRecordsByIdResponse.json
  example: !include Assets/examples/Response/AssetsSetRecordsByIdResponse.json

AssetsGetSubRecordsByIdRequest:
  schema: !include Assets/schemas/Request/AssetsGetSubRecordsByIdRequest.json
  example: !include Assets/examples/Request/AssetsGetSubRecordsByIdRequest.json
AssetsGetSubRecordsByIdResponse:
  schema: !include Assets/schemas/Response/AssetsGetSubRecordsByIdResponse.json
  example: !include Assets/examples/Response/AssetsGetSubRecordsByIdResponse.json


AssetsSetSubRecordsByIdRequest:
  schema: !include Assets/schemas/Request/AssetsSetSubRecordsByIdRequest.json
  example: !include Assets/examples/Request/AssetsSetSubRecordsByIdRequest.json
AssetsSetSubRecordsByIdResponse:
  schema: !include Assets/schemas/Response/AssetsSetSubRecordsByIdResponse.json
  example: !include Assets/examples/Response/AssetsSetSubRecordsByIdResponse.json

#=================================================================================


#=============================
# Entities for Machines   - This is not implemented completely, kept just for reference
#=============================


MachineGetSetNameRequest:
  schema: !include Machine/schemas/Request/MachineGetSetNameRequest.json
  example: !include Machine/examples/Request/MachineGetSetNameRequest.json
MachineGetSetNameReResponse:
  schema: !include Machine/schemas/Response/MachineGetSetNameReResponse.json
  example: !include Machine/examples/Response/MachineGetSetNameReResponse.json

MachineGetSetRecordsByIdRequest:
  schema: !include Machine/schemas/Request/MachineGetSetRecordsByIdRequest.json
  example: !include Machine/examples/Request/MachineGetSetRecordsByIdRequest.json
MachineGetSetRecordsByIdResponse:
  schema: !include Machine/schemas/Response/MachineGetSetRecordsByIdResponse.json
  example: !include Machine/examples/Response/MachineGetSetRecordsByIdResponse.json

MachineGetSetSubRecordsByIdRequest:
  schema: !include Machine/schemas/Request/MachineGetSetSubRecordsByIdRequest.json
  example: !include Machine/examples/Request/MachineGetSetSubRecordsByIdRequest.json
MachineGetSetSubRecordsByIdResponse:
  schema: !include Machine/schemas/Response/MachineGetSetSubRecordsByIdResponse.json
  example: !include Machine/examples/Response/MachineGetSetSubRecordsByIdResponse.json

#=================================================================================


#=============================
# Entities for Human - This is not implemented completely, kept just for reference
#=============================
HumanGetSetNameRequest:
  schema: !include Human/schemas/Request/HumanGetSetNameRequest.json
  example: !include Human/examples/Request/HumanGetSetNameRequest.json
HumanGetSetNameReResponse:
  schema: !include Human/schemas/Response/HumanGetSetNameReResponse.json
  example: !include Human/examples/Response/HumanGetSetNameReResponse.json

HumanGetSetRecordsByIdRequest:
  schema: !include Human/schemas/Request/HumanGetSetRecordsByIdRequest.json
  example: !include Human/examples/Request/HumanGetSetRecordsByIdRequest.json
HumanGetSetRecordsByIdResponse:
  schema: !include Human/schemas/Response/HumanGetSetRecordsByIdResponse.json
  example: !include Human/examples/Response/HumanGetSetRecordsByIdResponse.json

HumanGetSetSubRecordsByIdRequest:
  schema: !include Human/schemas/Request/HumanGetSetSubRecordsByIdRequest.json
  example: !include Human/examples/Request/HumanGetSetSubRecordsByIdRequest.json
HumanGetSetSubRecordsByIdResponse:
  schema: !include Human/schemas/Response/HumanGetSetSubRecordsByIdResponse.json
  example: !include Human/examples/Response/HumanGetSetSubRecordsByIdResponse.json
#=================================================================================
